### ISSUE TITLE
Hello, I want to download the synthetic shadow image and the corresponding mask, can you help me to open the permission of google drive? thanks

### ISSUE THREAD

**Issue by cjt222** [IsHYuhi/DSRFGD#3]
Hello, I want to download the synthetic shadow image and the corresponding mask in FSDSRD, can you help me to open the permission of google drive? thanks

**Comment by IsHYuhi** [comment]
Hello, I accepted you to access the dataset.
If you have any problems, please let me know.

Thanks.

**Comment by Testhjf** [comment]
can you share dataset on baidu 云盘  ，thanks！！！！
