### ISSUE TITLE
About the [textures] and [backgrounds]

### ISSUE THREAD

**Issue by igodogi** [IsHYuhi/DSRFGD#6]
Can you provide more information about _data/textures/_ and _data/backgrounds/_?
Where should I download it?  
What kind of files are downloaded?  
How to use it? 

Or can you directly open these two folders for our reproduction and reference

**Comment by IsHYuhi** [comment]
Sorry for the late reply.

For _textures_, please use free downloadable images that can be found by searching for "paper texture images" or similar. We scraped the images from the web. _backgrounds_ are also used images such as wood, concrete, etc.

We also created a new, updated synthetic dataset for shadow removal. It will be available soon, and we will inform you when it is available.
