### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by xuhangc** [IsHYuhi/DSRFGD#8]
Would you mind elaborating on the three dataset train/test split presented in the paper?

**Comment by IsHYuhi** [comment]
I'm sorry for not getting back to you sooner.

The data split is as follows,

Jung
test: 1-30, the # of pairs is 30
train & val: random, the # of pairs is 57

OSR
train: \~014, the # of pairs is 163
validation: 015, 016, the # of pairs is 28
test: 017\~026, the # of pairs is 46


The synthetic data was not used in testing.

Thank you.
